/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsuariosIndexRouteImport } from './routes/usuarios/index'
import { Route as ReivindicacoesIndexRouteImport } from './routes/reivindicacoes/index'
import { Route as PerfilIndexRouteImport } from './routes/perfil/index'
import { Route as PedidosIndexRouteImport } from './routes/pedidos/index'
import { Route as MapasLiterariosIndexRouteImport } from './routes/mapas-literarios/index'
import { Route as LivrosIndexRouteImport } from './routes/livros/index'
import { Route as HeroSlidesIndexRouteImport } from './routes/hero-slides/index'
import { Route as ContaIndexRouteImport } from './routes/conta/index'
import { Route as AutoresIndexRouteImport } from './routes/autores/index'
import { Route as AtividadeIndexRouteImport } from './routes/atividade/index'
import { Route as ArtigosIndexRouteImport } from './routes/artigos/index'
import { Route as PerfilReivindicarRouteImport } from './routes/perfil/reivindicar'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as ArtigosNovoRouteImport } from './routes/artigos/novo'
import { Route as ArtigosIdEditarRouteImport } from './routes/artigos/$id/editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosIndexRoute = UsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReivindicacoesIndexRoute = ReivindicacoesIndexRouteImport.update({
  id: '/reivindicacoes/',
  path: '/reivindicacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapasLiterariosIndexRoute = MapasLiterariosIndexRouteImport.update({
  id: '/mapas-literarios/',
  path: '/mapas-literarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosIndexRoute = LivrosIndexRouteImport.update({
  id: '/livros/',
  path: '/livros/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroSlidesIndexRoute = HeroSlidesIndexRouteImport.update({
  id: '/hero-slides/',
  path: '/hero-slides/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaIndexRoute = ContaIndexRouteImport.update({
  id: '/conta/',
  path: '/conta/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoresIndexRoute = AutoresIndexRouteImport.update({
  id: '/autores/',
  path: '/autores/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadeIndexRoute = AtividadeIndexRouteImport.update({
  id: '/atividade/',
  path: '/atividade/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosIndexRoute = ArtigosIndexRouteImport.update({
  id: '/artigos/',
  path: '/artigos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilReivindicarRoute = PerfilReivindicarRouteImport.update({
  id: '/perfil/reivindicar',
  path: '/perfil/reivindicar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosNovoRoute = ArtigosNovoRouteImport.update({
  id: '/artigos/novo',
  path: '/artigos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosIdEditarRoute = ArtigosIdEditarRouteImport.update({
  id: '/artigos/$id/editar',
  path: '/artigos/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artigos/novo': typeof ArtigosNovoRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/perfil/reivindicar': typeof PerfilReivindicarRoute
  '/artigos/': typeof ArtigosIndexRoute
  '/atividade/': typeof AtividadeIndexRoute
  '/autores/': typeof AutoresIndexRoute
  '/conta/': typeof ContaIndexRoute
  '/hero-slides/': typeof HeroSlidesIndexRoute
  '/livros/': typeof LivrosIndexRoute
  '/mapas-literarios/': typeof MapasLiterariosIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/reivindicacoes/': typeof ReivindicacoesIndexRoute
  '/usuarios/': typeof UsuariosIndexRoute
  '/artigos/$id/editar': typeof ArtigosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artigos/novo': typeof ArtigosNovoRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/perfil/reivindicar': typeof PerfilReivindicarRoute
  '/artigos': typeof ArtigosIndexRoute
  '/atividade': typeof AtividadeIndexRoute
  '/autores': typeof AutoresIndexRoute
  '/conta': typeof ContaIndexRoute
  '/hero-slides': typeof HeroSlidesIndexRoute
  '/livros': typeof LivrosIndexRoute
  '/mapas-literarios': typeof MapasLiterariosIndexRoute
  '/pedidos': typeof PedidosIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/reivindicacoes': typeof ReivindicacoesIndexRoute
  '/usuarios': typeof UsuariosIndexRoute
  '/artigos/$id/editar': typeof ArtigosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artigos/novo': typeof ArtigosNovoRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/perfil/reivindicar': typeof PerfilReivindicarRoute
  '/artigos/': typeof ArtigosIndexRoute
  '/atividade/': typeof AtividadeIndexRoute
  '/autores/': typeof AutoresIndexRoute
  '/conta/': typeof ContaIndexRoute
  '/hero-slides/': typeof HeroSlidesIndexRoute
  '/livros/': typeof LivrosIndexRoute
  '/mapas-literarios/': typeof MapasLiterariosIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/reivindicacoes/': typeof ReivindicacoesIndexRoute
  '/usuarios/': typeof UsuariosIndexRoute
  '/artigos/$id/editar': typeof ArtigosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artigos/novo'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/perfil/reivindicar'
    | '/artigos/'
    | '/atividade/'
    | '/autores/'
    | '/conta/'
    | '/hero-slides/'
    | '/livros/'
    | '/mapas-literarios/'
    | '/pedidos/'
    | '/perfil/'
    | '/reivindicacoes/'
    | '/usuarios/'
    | '/artigos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artigos/novo'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/perfil/reivindicar'
    | '/artigos'
    | '/atividade'
    | '/autores'
    | '/conta'
    | '/hero-slides'
    | '/livros'
    | '/mapas-literarios'
    | '/pedidos'
    | '/perfil'
    | '/reivindicacoes'
    | '/usuarios'
    | '/artigos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/artigos/novo'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/perfil/reivindicar'
    | '/artigos/'
    | '/atividade/'
    | '/autores/'
    | '/conta/'
    | '/hero-slides/'
    | '/livros/'
    | '/mapas-literarios/'
    | '/pedidos/'
    | '/perfil/'
    | '/reivindicacoes/'
    | '/usuarios/'
    | '/artigos/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtigosNovoRoute: typeof ArtigosNovoRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  PerfilReivindicarRoute: typeof PerfilReivindicarRoute
  ArtigosIndexRoute: typeof ArtigosIndexRoute
  AtividadeIndexRoute: typeof AtividadeIndexRoute
  AutoresIndexRoute: typeof AutoresIndexRoute
  ContaIndexRoute: typeof ContaIndexRoute
  HeroSlidesIndexRoute: typeof HeroSlidesIndexRoute
  LivrosIndexRoute: typeof LivrosIndexRoute
  MapasLiterariosIndexRoute: typeof MapasLiterariosIndexRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  ReivindicacoesIndexRoute: typeof ReivindicacoesIndexRoute
  UsuariosIndexRoute: typeof UsuariosIndexRoute
  ArtigosIdEditarRoute: typeof ArtigosIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/': {
      id: '/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof UsuariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reivindicacoes/': {
      id: '/reivindicacoes/'
      path: '/reivindicacoes'
      fullPath: '/reivindicacoes/'
      preLoaderRoute: typeof ReivindicacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas-literarios/': {
      id: '/mapas-literarios/'
      path: '/mapas-literarios'
      fullPath: '/mapas-literarios/'
      preLoaderRoute: typeof MapasLiterariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros/': {
      id: '/livros/'
      path: '/livros'
      fullPath: '/livros/'
      preLoaderRoute: typeof LivrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-slides/': {
      id: '/hero-slides/'
      path: '/hero-slides'
      fullPath: '/hero-slides/'
      preLoaderRoute: typeof HeroSlidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/': {
      id: '/conta/'
      path: '/conta'
      fullPath: '/conta/'
      preLoaderRoute: typeof ContaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autores/': {
      id: '/autores/'
      path: '/autores'
      fullPath: '/autores/'
      preLoaderRoute: typeof AutoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividade/': {
      id: '/atividade/'
      path: '/atividade'
      fullPath: '/atividade/'
      preLoaderRoute: typeof AtividadeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos/': {
      id: '/artigos/'
      path: '/artigos'
      fullPath: '/artigos/'
      preLoaderRoute: typeof ArtigosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/reivindicar': {
      id: '/perfil/reivindicar'
      path: '/perfil/reivindicar'
      fullPath: '/perfil/reivindicar'
      preLoaderRoute: typeof PerfilReivindicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos/novo': {
      id: '/artigos/novo'
      path: '/artigos/novo'
      fullPath: '/artigos/novo'
      preLoaderRoute: typeof ArtigosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos/$id/editar': {
      id: '/artigos/$id/editar'
      path: '/artigos/$id/editar'
      fullPath: '/artigos/$id/editar'
      preLoaderRoute: typeof ArtigosIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtigosNovoRoute: ArtigosNovoRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  PerfilReivindicarRoute: PerfilReivindicarRoute,
  ArtigosIndexRoute: ArtigosIndexRoute,
  AtividadeIndexRoute: AtividadeIndexRoute,
  AutoresIndexRoute: AutoresIndexRoute,
  ContaIndexRoute: ContaIndexRoute,
  HeroSlidesIndexRoute: HeroSlidesIndexRoute,
  LivrosIndexRoute: LivrosIndexRoute,
  MapasLiterariosIndexRoute: MapasLiterariosIndexRoute,
  PedidosIndexRoute: PedidosIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  ReivindicacoesIndexRoute: ReivindicacoesIndexRoute,
  UsuariosIndexRoute: UsuariosIndexRoute,
  ArtigosIdEditarRoute: ArtigosIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
