/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsuariosIndexRouteImport } from './routes/usuarios/index'
import { Route as ReivindicacoesIndexRouteImport } from './routes/reivindicacoes/index'
import { Route as PedidosIndexRouteImport } from './routes/pedidos/index'
import { Route as MapasLiterariosIndexRouteImport } from './routes/mapas-literarios/index'
import { Route as LivrosIndexRouteImport } from './routes/livros/index'
import { Route as HeroSlidesIndexRouteImport } from './routes/hero-slides/index'
import { Route as AutoresIndexRouteImport } from './routes/autores/index'
import { Route as ArtigosIndexRouteImport } from './routes/artigos/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosIndexRoute = UsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReivindicacoesIndexRoute = ReivindicacoesIndexRouteImport.update({
  id: '/reivindicacoes/',
  path: '/reivindicacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapasLiterariosIndexRoute = MapasLiterariosIndexRouteImport.update({
  id: '/mapas-literarios/',
  path: '/mapas-literarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosIndexRoute = LivrosIndexRouteImport.update({
  id: '/livros/',
  path: '/livros/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroSlidesIndexRoute = HeroSlidesIndexRouteImport.update({
  id: '/hero-slides/',
  path: '/hero-slides/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoresIndexRoute = AutoresIndexRouteImport.update({
  id: '/autores/',
  path: '/autores/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosIndexRoute = ArtigosIndexRouteImport.update({
  id: '/artigos/',
  path: '/artigos/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artigos/': typeof ArtigosIndexRoute
  '/autores/': typeof AutoresIndexRoute
  '/hero-slides/': typeof HeroSlidesIndexRoute
  '/livros/': typeof LivrosIndexRoute
  '/mapas-literarios/': typeof MapasLiterariosIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/reivindicacoes/': typeof ReivindicacoesIndexRoute
  '/usuarios/': typeof UsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosIndexRoute
  '/autores': typeof AutoresIndexRoute
  '/hero-slides': typeof HeroSlidesIndexRoute
  '/livros': typeof LivrosIndexRoute
  '/mapas-literarios': typeof MapasLiterariosIndexRoute
  '/pedidos': typeof PedidosIndexRoute
  '/reivindicacoes': typeof ReivindicacoesIndexRoute
  '/usuarios': typeof UsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artigos/': typeof ArtigosIndexRoute
  '/autores/': typeof AutoresIndexRoute
  '/hero-slides/': typeof HeroSlidesIndexRoute
  '/livros/': typeof LivrosIndexRoute
  '/mapas-literarios/': typeof MapasLiterariosIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/reivindicacoes/': typeof ReivindicacoesIndexRoute
  '/usuarios/': typeof UsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artigos/'
    | '/autores/'
    | '/hero-slides/'
    | '/livros/'
    | '/mapas-literarios/'
    | '/pedidos/'
    | '/reivindicacoes/'
    | '/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artigos'
    | '/autores'
    | '/hero-slides'
    | '/livros'
    | '/mapas-literarios'
    | '/pedidos'
    | '/reivindicacoes'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/artigos/'
    | '/autores/'
    | '/hero-slides/'
    | '/livros/'
    | '/mapas-literarios/'
    | '/pedidos/'
    | '/reivindicacoes/'
    | '/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtigosIndexRoute: typeof ArtigosIndexRoute
  AutoresIndexRoute: typeof AutoresIndexRoute
  HeroSlidesIndexRoute: typeof HeroSlidesIndexRoute
  LivrosIndexRoute: typeof LivrosIndexRoute
  MapasLiterariosIndexRoute: typeof MapasLiterariosIndexRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
  ReivindicacoesIndexRoute: typeof ReivindicacoesIndexRoute
  UsuariosIndexRoute: typeof UsuariosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/': {
      id: '/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof UsuariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reivindicacoes/': {
      id: '/reivindicacoes/'
      path: '/reivindicacoes'
      fullPath: '/reivindicacoes/'
      preLoaderRoute: typeof ReivindicacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas-literarios/': {
      id: '/mapas-literarios/'
      path: '/mapas-literarios'
      fullPath: '/mapas-literarios/'
      preLoaderRoute: typeof MapasLiterariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros/': {
      id: '/livros/'
      path: '/livros'
      fullPath: '/livros/'
      preLoaderRoute: typeof LivrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-slides/': {
      id: '/hero-slides/'
      path: '/hero-slides'
      fullPath: '/hero-slides/'
      preLoaderRoute: typeof HeroSlidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autores/': {
      id: '/autores/'
      path: '/autores'
      fullPath: '/autores/'
      preLoaderRoute: typeof AutoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos/': {
      id: '/artigos/'
      path: '/artigos'
      fullPath: '/artigos/'
      preLoaderRoute: typeof ArtigosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtigosIndexRoute: ArtigosIndexRoute,
  AutoresIndexRoute: AutoresIndexRoute,
  HeroSlidesIndexRoute: HeroSlidesIndexRoute,
  LivrosIndexRoute: LivrosIndexRoute,
  MapasLiterariosIndexRoute: MapasLiterariosIndexRoute,
  PedidosIndexRoute: PedidosIndexRoute,
  ReivindicacoesIndexRoute: ReivindicacoesIndexRoute,
  UsuariosIndexRoute: UsuariosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
